# Generated by Django 6.0.3 on 2026-04-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_engine', '0002_clientadvisor_clientassignmentdefinition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekly_flags',
            name='archetype',
        ),
        migrations.AddField(
            model_name='weekly_metrics',
            name='risk_score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pre_sem_watchlist',
            name='assn_rate_hist',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pre_sem_watchlist',
            name='att_rate_hist',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='pre_sem_watchlist',
            name='exam_avg_hist',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
