# Generated by Django 6.0.3 on 2026-04-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_engine', '0003_remove_weekly_flags_archetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekly_flags',
            name='generate_content_command',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='weekly_flags',
            name='suggested_intervention',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='weekly_flags',
            name='suggestion_computed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='weekly_flags',
            name='suggestion_reasoning',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
