# Generated by Django 6.0.3 on 2026-04-15 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_engine', '0004_weekly_flags_generate_content_command_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekly_flags',
            name='generate_content_command',
        ),
        migrations.RemoveField(
            model_name='weekly_flags',
            name='suggested_intervention',
        ),
        migrations.RemoveField(
            model_name='weekly_flags',
            name='suggestion_computed_at',
        ),
        migrations.RemoveField(
            model_name='weekly_flags',
            name='suggestion_reasoning',
        ),
    ]
