# Generated by Django 6.0.3 on 2026-04-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis_engine', '0005_remove_weekly_flags_generate_content_command_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='weekly_flags',
            name='idx_wf_student',
        ),
        migrations.RemoveIndex(
            model_name='weekly_metrics',
            name='idx_wm_student',
        ),
        migrations.RenameIndex(
            model_name='weekly_flags',
            new_name='weekly_flag_class_i_4e9756_idx',
            old_name='idx_wf_class_sem_week',
        ),
        migrations.RenameIndex(
            model_name='weekly_metrics',
            new_name='weekly_metr_class_i_cc4152_idx',
            old_name='idx_wm_class_sem_week',
        ),
        migrations.AddIndex(
            model_name='weekly_flags',
            index=models.Index(fields=['student_id', 'semester'], name='weekly_flag_student_7110e5_idx'),
        ),
        migrations.AddIndex(
            model_name='weekly_metrics',
            index=models.Index(fields=['student_id', 'semester', 'sem_week'], name='weekly_metr_student_976802_idx'),
        ),
    ]
